# Un-comment this option out, if you'd like players to require a specific
# permission to use the custom enchanting table
# custom_enchanting_table_permission: custom_enchanting.use

# Determines the maximum amount of power an enchanting table can have.
# Power is determined by how many bookshelves are placed around the enchanting table.
max_enchanting_table_power: 300

# How much power an enchanting table will receive when a bookshelf is placed
# 1 block near it.
#
# An enchanting table's power may determine what enchants are available (depending on how you configure them in the eenchants config).
power_per_bookshelf: 5

# If a chiseled bookshelf is placed near, this is how much power the enchanting table
# will receive per normal book that is placed in the chiseled bookshelf
power_per_book_in_chiseled_bookshelf: 1
# Just like the per_book option, this is for enchanted books
power_per_enchanted_book_in_chiseled_bookshelf: 2
# For each enchanted book that is placed in a chiseled bookshelf near an enchanting table,
# the "progress" is calculated by: <level> / <max_level> (e.i., Sharpness III book would be: 3/5 = 0.6)
#
# Then that progress value is multiplied by this config option (e.i, Sharpness III = 0.6 * 3 = 2 (output is rounded))
power_per_enchant_on_enchanted_book_progress: 3
