[plugins]
kotlin = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "run_paper" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
crunch = { group = "com.github.Redempt", name = "Crunch", version.ref = "crunch" }

[versions]
shadow = "9.4.1"
paperweight = "2.0.0-beta.23"
paper = "26.2.build.124-stable"
kotlin = "2.3.20"
run_paper = "3.0.2"
crunch = "2.0.3"